version: "3.8"

services:
  app:
    build: .
    command: poetry run pytest
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/myapp
    networks:
      - mynet

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: myapp
    ports:
      - "5432:5432"
    networks:
      - mynet

networks:
  mynet:
