services:
  web:
    build: .
    command: uvicorn myapp.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./src:/app/src
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379/0
  celery:
    build: .
    command: celery -A myapp.worker worker --loglevel=info
    volumes:
      - ./src:/app/src
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379/0


  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
